# Generated by Django 2.2 on 2020-08-13 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_oembed', '0003_remove_videopluginmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_oembed_videopluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='videopluginmodel',
            name='max_width',
            field=models.IntegerField(blank=True, help_text='in px', null=True),
        ),
    ]
